### ISSUE TITLE
NEXT_WORD egdes still missing

### ISSUE THREAD

**Issue by kuczera** [sarmbruster/neo4j-apoc-procedures#3]
I have compiled a new lib, installed it but the NEXT_WORD edge does not appear after import of a xml-file.

**Comment by sarmbruster** [comment]
sorry, forgot to mention: creating NEXT_WORD is a optional step, requiring some configuration:
```call apoc.xml.import("file:///var/lib/neo4j/import/h.xml",{createNextWorkRelationships: true}) yield node return node```
After the URL you need to supply a map with the given contents.
